name: Docker Image CI
on: [push]

env:
  TAG_NAME: latest
  ARTIFACT_NAME: selenium-chrome
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/selenium-chrome

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
          outputs: type=docker,dest=/tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp/${{ env.ARTIFACT_NAME }}.tar

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Run test
        run: |
          docker run --rm --name test-${{ env.ARTIFACT_NAME }} -v $(pwd)/tests/:/tmp/ \
          ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} \
          /bin/sh -c "python /tmp/test-${{ env.ARTIFACT_NAME }}.py"

  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Upload Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
